---
abstract: 'Networked Help Desk protocol for Request Tracker'
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.57
configure_requires:
  ExtUtils::MakeMaker: 6.57
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-NHD
no_index:
  directory:
    - etc
    - html
    - inc
    - t
requires:
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
